// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel diffLeftRight
#pragma kernel maxDifference

#pragma kernel flattenValues


StructuredBuffer<float> leftOverlayData;
StructuredBuffer<float> rightOverlayData;

RWStructuredBuffer<float> outputDifference;
RWStructuredBuffer<float> maxOutputDifference;


[numthreads(64,1,1)]
void diffLeftRight (uint3 id : SV_DispatchThreadID)
{
    uint x = id.x;
    
    float vd = leftOverlayData[x] - rightOverlayData[x];
    outputDifference[x] = vd * vd;
    
}

[numthreads(64,1,1)]
void maxDifference(uint3 id : SV_DispatchThreadID)
{
    uint x = id.x;
    maxOutputDifference[x] = rightOverlayData[x] * rightOverlayData[x];
   
}


StructuredBuffer<float> overlayData;
RWStructuredBuffer<float> flattenedData;

[numthreads(64, 1, 1)]
void flattenValues(uint3 id : SV_DispatchThreadID)
{
    uint x = id.x;
    uint index = id.x * 4;
    float R = overlayData[index];
    float G = overlayData[index + 1];
    float B = overlayData[index + 2];
    float A = overlayData[index + 3];
    
    float flattenedValue = (R + G + B + A) / 4;
    
    flattenedData[x] = flattenedValue;

}