// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel SegmentPatches

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

RWStructuredBuffer<float4> outputPatches;

float imgHeight;
float imgWidth;

float heightIgnore;
float widthIgnore;

// total number of patches on x axis
int numRowPatches;
// total number of patches on y axis
int numColPatches;
// dimensions of a patch
int sizePatch;

// our current processing patch
int currentPatchHorizontal;
int currentPatchVertical;

StructuredBuffer<float> pixelData;




[numthreads(8,8,1)]
void SegmentPatches (uint3 id : SV_DispatchThreadID)
{
    // positions of pixel based on how large a patch is
    uint x = id.x;
    uint y = id.y;
    // global position of our pixel
    uint globalPositionX = x + currentPatchHorizontal * sizePatch;
    uint globalPositionY = y + currentPatchVertical * sizePatch;
    
    // pixel position in the 1D array of pixels
    int pixelInArray = globalPositionY * (imgWidth * 4) + globalPositionX * 4;
    
    // get the pixel from the input array of pixels based on the global position
    float4 currentPixel = float4(pixelData[pixelInArray + 0], pixelData[pixelInArray + 1], pixelData[pixelInArray + 2], pixelData[pixelInArray + 3]);
    
    // choose location of pixel to be stored in in the output array
    int outputIndex = y * sizePatch + x;
    
    // save pixel into the output buffer
    outputPatches[outputIndex] = currentPixel;
   
}


// for my reference
// https://www.youtube.com/watch?v=XyUusirGAl4&ab_channel=Arsiliath



//(imgWidth * 4 - widthIgnore) && y
    
    // check if pixel is outside the confineded patch spaces
    // y
    
    // get position of the patch that the current pixel should be in
    //int horizontalPatch = x / numRowPatches;
    //int horizontalPatch = x * (numRowPatches / (sizePatch * numRowPatches));
    
    //int horizontalPatch = x / sizePatch;
    //int verticalPatch = y / sizePatch;
    //int patchIndex = horizontalPatch * verticalPatch;