// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel extractTopOverlays
#pragma kernel extractLeftOverlays
#pragma kernel extractBottOverlays
#pragma kernel extractRightOverlays

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

RWStructuredBuffer<float4> topOverlayOutput;
RWStructuredBuffer<float4> leftOverlayOutput;
RWStructuredBuffer<float4> bottomOverlayOutput;
RWStructuredBuffer<float4> rightOverlayOutput;

// input patch data for data processing
StructuredBuffer<float> patchData;

// the number of rows that should be added
int overlapSize;
// patch size
int patchSize;
// patch size - overlap size
int truePatchSize;

// debug for condition
RWStructuredBuffer<int> condition_debug;

[numthreads(8,8,1)]
void extractTopOverlays (uint3 id : SV_DispatchThreadID)
{
    // positions of pixel based on how large a patch is
    uint x = id.x;
    uint y = id.y;
    
    if (x >= patchSize || y >= patchSize)
        return;
    
    
    if (patchSize - y <= overlapSize && x >= overlapSize)
    {
        
        // pixel position in the 1D array of pixels
        int pixelInArray = y * (patchSize * 4) + x * 4;
        
        // get the pixel from the input array of pixels based on the global position
        float4 currentPixel = float4(patchData[pixelInArray + 0], patchData[pixelInArray + 1], patchData[pixelInArray + 2], patchData[pixelInArray + 3]);
        
        // get index
        int outputIndex = (y - (patchSize - overlapSize)) * truePatchSize + (x - overlapSize);
        condition_debug[y * patchSize + x] = outputIndex;
        // save pixel into the output buffer
        topOverlayOutput[outputIndex] = currentPixel;
        
        
    }
}

[numthreads(8,8,1)]
void extractLeftOverlays(uint3 id : SV_DispatchThreadID)
{
    // positions of pixel based on how large a patch is
    uint x = id.x;
    uint y = id.y;
    
    if (x >= patchSize || y >= patchSize)
        return;
    
    // only save pixels at the most left side
    if (x < overlapSize)
    {
        // pixel position in the 1D array of pixels
        int pixelInArray = y * (patchSize * 4) + x * 4;
        
        // get the pixel from the input array of pixels based on the global position
        float4 currentPixel = float4(patchData[pixelInArray + 0], patchData[pixelInArray + 1], patchData[pixelInArray + 2], patchData[pixelInArray + 3]);
        
        // get index
        int outputIndex = y * overlapSize + x;
        
        condition_debug[y * patchSize + x] = outputIndex;
        // save pixel into the output buffer
        leftOverlayOutput[outputIndex] = currentPixel;
    }
}

[numthreads(8,8,1)]
void extractBottOverlays(uint3 id : SV_DispatchThreadID)
{
    // positions of pixel based on how large a patch is
    uint x = id.x;
    uint y = id.y;
    
    if (x >= patchSize || y >= patchSize)
        return;
    
    if (y <= overlapSize && x >= overlapSize)
    {
        // pixel position in the 1D array of pixels
        int pixelInArray = y * (patchSize * 4) + x * 4;
        
        // get the pixel from the input array of pixels based on the global position
        float4 currentPixel = float4(patchData[pixelInArray + 0], patchData[pixelInArray + 1], patchData[pixelInArray + 2], patchData[pixelInArray + 3]);
        
        // get index
        int outputIndex = y * truePatchSize + (x - overlapSize);
        
        // save pixel into the output buffer
        bottomOverlayOutput[outputIndex] = currentPixel;
        
    }
    
}

[numthreads(8, 8, 1)]
void extractRightOverlays(uint3 id : SV_DispatchThreadID)
{
    // positions of pixel based on how large a patch is
    uint x = id.x;
    uint y = id.y;
    
    if (x >= patchSize || y >= patchSize)
        return;
    
    // only save pixels at the most left side
    if (patchSize - x <= overlapSize && y <= patchSize - overlapSize)
    {
        // pixel position in the 1D array of pixels
        int pixelInArray = y * (patchSize * 4) + x * 4;
        
        // get the pixel from the input array of pixels based on the global position
        float4 currentPixel = float4(patchData[pixelInArray + 0], patchData[pixelInArray + 1], patchData[pixelInArray + 2], patchData[pixelInArray + 3]);
        
        // get index
        int outputIndex = y * overlapSize + (x - (truePatchSize));

       
        // save pixel into the output buffer
        rightOverlayOutput[outputIndex] = currentPixel;
    }
}

