// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel ReadPixel

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

Texture2D<float4> inputTexture;

float img_height;
float img_width;

RWStructuredBuffer<float4> outputBuffer;

// how thread groups are used
[numthreads(8,8,1)]
void ReadPixel (uint3 id : SV_DispatchThreadID)
{
    uint x = id.x;
    uint y = id.y;
    
    // Calculate the 1D index in the buffer
    int index = y * img_width + x;

    // Read the pixel colour from the texture
    float4 color = inputTexture.Load(int3(x, y, 0));

    // Store the pixel data in the buffer
    outputBuffer[index] = color;
    
    
    
    /*int increment = 0;
    for (int y = 0; y < img_height; y++)
    {
        for (int x = 0; x < img_width; x++)
        {
            float4 color = inputTexture.Load(int3(x, y, 0));
            
            outputBuffer[increment] = color;

        }
            
    }*/
        

    
}
